runtime: nodejs18
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

entrypoint: npm start

env_variables:
  PORT: 8080  # der Port, auf dem der App Engine-Proxy auf Anfragen hört

handlers:
  - url: /(.*\.(js|css|map|json|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|ico))
    static_files: dist/programmierprojekt/\1
    upload: dist/programmierprojekt/.*\.(js|css|map|json|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|ico)$

  # Alle anderen URLs werden an die Angular-App weitergeleitet
  - url: /.*
    static_files: dist/programmierprojekt/index.html
    upload: dist/programmierprojekt/index.html
    http_headers:
      Cache-Control: "no-cache, must-revalidate"
