runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /.*
    secure: always
    static_files: dist/programmierprojekt/index.html
    upload: dist/programmierprojekt/index.html
  - url: /.*
    secure: always
    static_dir: dist/programmierprojekt

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
