name: Synchronize Branches

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.DANIELPAT }}
          ref: main
          fetch-depth: 0  # Fetch all history for all branches and tags.

      - name: Push to test-deployment branch
        run: |
          git push origin HEAD:refs/heads/test-deployment
