name: Unit-Tests # Diese GitHub-Action muss erfolgreich durchlaufen, sonst darf keine PR gemergt werden

on:
  push:
    branches:
      - '**'  # Wird für jeden Push auf jeden Branch durchgeführt

jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test
